### ISSUE TITLE
Usage with Phoenix

### ISSUE THREAD

**Issue by stormpat** [jazzyb/sqlite_ecto#32]
So im testing out Elixir/Phoenix and have a old project with a sqlite database, im thinking of reusing the same database, but there is conflicts in the ecto version Phoenix wants to use and the on required by sqlite_ecto. So basically im wondering if sqlite_ecto has support/any issues with ecto 13.0/14.0?

```
Looking up alternatives for conflicting requirements on ecto
From mix.lock: 0.13.0
From sqlite_ecto v0.2.0: ~> 0.12.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

**Comment by stormpat** [comment]
Oh, never mind, i missed the ecto-13.0 branch :+1:

**Comment by jazzyb** [comment]
FYI:  I'll be pulling the 0.13 branch into master today and releasing a hex package, so you should be able to install the normal route by tomorrow.

**Comment by stormpat** [comment]
Thats great! Thank you!

**Comment by jazzyb** [comment]
Have at it: https://hex.pm/packages/sqlite_ecto/0.3.0 :)
