### ISSUE TITLE
"db" directory is not created when generating a new phoenix app using --database sqlite

### ISSUE THREAD

**Issue by rbenaley** [jazzyb/sqlite_ecto#36]
When I created a new app using "mix phoenix.new myapp --database sqlite" then I executed "cd myapp && mix ecto.create" the task has finished with the following error:

*\* (Mix) The database for Myapp.Repo couldn't be created, reason given: {:cantopen, 'unable to open database file'}.

After inspecting the end of the file "myapp/config/dev.exs" I can see that the database adapter configuration is correct:
# Configure your database

config :myapp, Myapp.Repo,
adapter: Sqlite.Ecto,
database: "db/myapp_dev.sqlite",
pool_size: 10

But the "db" directory does not exist in the application directory.

The workaround is to create the "db" directory prior executing "mix ecto.create", it would be desirable to fix that issue.

Affected and used version: 1.0.0

**Comment by rbenaley** [comment]
This issue was initially reported to the Phoenix team by mistake.

Ref. https://github.com/phoenixframework/phoenix/issues/1167

**Comment by jazzyb** [comment]
Thanks!

**Comment by jazzyb** [comment]
FYI:  Fix is on hex: https://hex.pm/packages/sqlite_ecto/1.0.1
