### ISSUE TITLE
Modifying a field's value?

### ISSUE THREAD

**Issue by ghost** [jazzyb/sqlite_ecto#42]
Hi @jazzyb ! I was reading the basic tutorial and I saw

> Sqlite.Ecto can only add columns to tables -- it cannot remove or modify columns once they have been created.

I am working on a [project](https://github.com/Annwenn/Exon) of mine where people have to be able to add data to an item (the `comments` field, to be precise).
Do I have to understand that it won't be possible? Or am I misunderstanding any workaround?

**Comment by jazzyb** [comment]
Hi @Annwenn!

Sorry for taking so long to reply.  I've been out of pocket for a while.

SQLite cannot modify the name or type of a column once the table has already been created.  However, it sounds like what you want is to add items to the `comments` column of a table.  In this case, SQLite operates just like a normal SQL database.
